In [102]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [103]:
sample = pd.read_csv ("C:\\Users\\bubbl\\Desktop\\Data\\sample_submission.csv")
test = pd.read_csv("C:\\Users\\bubbl\\Desktop\\Data\\test.csv")
train = pd.read_csv("C:\\Users\\bubbl\\Desktop\\Data\\train.csv")

In [104]:
test

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
0,37061,Male,19.0,0,0,No,Private,Rural,92.61,16.8,never smoked
1,42333,Male,53.0,0,0,Yes,Govt_job,Urban,94.03,26.5,NaN
2,58964,Female,51.0,0,0,Yes,Private,Rural,127.22,31.0,smokes
3,34063,Female,17.0,0,0,No,Private,Rural,112.15,19.8,NaN
4,43682,Female,41.0,0,0,Yes,Govt_job,Urban,112.17,27.5,never smoked
5,9789,Female,23.0,0,0,No,Private,Urban,86.54,28.1,smokes
6,6626,Female,21.0,0,0,Yes,Private,Urban,91.70,29.2,never smoked
7,12566,Female,42.0,0,0,Yes,Private,Urban,98.36,41.5,never smoked
8,27269,Female,37.0,0,0,Yes,Govt_job,Urban,94.59,30.0,NaN
9,47282,Female,19.0,0,0,No,Private,Rural,141.94,27.0,NaN
10,23349,Female,59.0,1,0,Yes,Private,Urban,96.97,19.8,smokes
11,34659,Female,54.0,0,0,Yes,Self-employed,Urban,89.30,33.0,never smoked
12,63488,Female,49.0,0,0,Yes,Self-employed,Rural,128.39,41.3,never smoked
13,69526,Male,30.0,0,0,Yes,Private,Rural,55.28,30.5,smokes
14,14741,Male,44.0,0,0,No,Govt_job,Rural,91.15,34.2,formerly smoked
15,1463,Female,52.0,0,0,Yes,Private,Urban,88.09,36.5,smokes
16,40038,Female,40.0,0,0,Yes,Private,Urban,85.49,26.4,never smoked
17,60343,Female,16.0,0,0,No,Private,Urban,146.83,25.4,never smoked
18,15557,Male,57.0,1,1,Yes,Private,Rural,92.73,33.4,formerly smoked
19,43345,Male,68.0,0,0,Yes,Self-employed,Rural,56.15,29.3,formerly smoked
20,31335,Female,49.0,0,0,Yes,Govt_job,Rural,73.21,35.8,NaN
21,17847,Male,77.0,0,1,Yes,Private,Urban,81.64,25.9,formerly smoked
22,14492,Female,27.0,0,0,Yes,Private,Rural,107.41,20.1,never smoked
23,14340,Female,66.0,0,0,Yes,Private,Urban,68.33,25.2,never smoked
24,54152,Female,77.0,0,0,Yes,Govt_job,Urban,181.30,27.0,smokes
25,12295,Female,75.0,1,0,Yes,Private,Urban,72.98,32.6,never smoked
26,40539,Female,25.0,0,0,No,Govt_job,Urban,72.77,19.9,NaN
27,26581,Male,29.0,0,0,Yes,Private,Urban,96.64,33.2,NaN
28,25700,Male,75.0,1,0,Yes,Private,Rural,226.27,27.1,never smoked
29,72040,Female,77.0,0,0,Yes,Govt_job,Rural,114.24,20.5,formerly smoked
...,...,...,...,...,...,...,...,...,...,...,...
13370,8908,Male,79.0,0,0,Yes,Self-employed,Rural,100.71,25.2,never smoked
13371,18119,Female,78.0,0,0,Yes,Private,Urban,182.45,NaN,formerly smoked
13372,45066,Male,36.0,1,0,Yes,Private,Urban,149.22,33.4,NaN
13373,2712,Female,46.0,0,0,No,Private,Rural,88.66,34.5,smokes
13374,35172,Male,49.0,0,0,Yes,Private,Rural,98.91,35.3,smokes
13375,51452,Female,70.0,0,0,Yes,Self-employed,Rural,121.45,27.3,never smoked
13376,65913,Female,3.0,0,0,No,children,Rural,83.32,21.3,NaN
13377,29122,Female,63.0,0,0,Yes,Govt_job,Urban,88.08,33.6,never smoked
13378,12555,Male,22.0,0,0,No,Private,Urban,86.82,30.2,never smoked
13379,13530,Male,47.0,0,1,Yes,Govt_job,Urban,89.25,29.0,NaN
13380,46293,Male,26.0,0,0,Yes,Private,Rural,71.31,25.3,formerly smoked
13381,57176,Male,45.0,0,0,Yes,Private,Urban,214.05,40.5,formerly smoked
13382,35179,Female,9.0,0,0,No,children,Urban,68.49,16.8,NaN
13383,38020,Male,18.0,0,0,No,Private,Urban,131.73,24.9,never smoked
13384,44814,Female,65.0,0,0,Yes,Private,Rural,200.92,30.7,formerly smoked
13385,5366,Female,66.0,0,0,Yes,Self-employed,Urban,92.10,24.8,NaN
13386,18828,Male,68.0,0,1,Yes,Private,Urban,113.60,25.5,never smoked
13387,25888,Male,20.0,0,0,No,Private,Rural,83.37,26.5,never smoked
13388,31321,Female,64.0,1,0,Yes,Govt_job,Rural,228.43,NaN,smokes
13389,30759,Male,14.0,0,0,No,children,Urban,82.48,24.8,NaN
13390,10096,Female,69.0,0,0,Yes,Self-employed,Urban,229.85,31.2,never smoked
13391,30077,Male,6.0,0,0,No,children,Urban,77.48,19.1,NaN
13392,45266,Female,18.0,0,0,No,Private,Urban,131.96,22.8,NaN
13393,69344,Male,39.0,0,0,Yes,Private,Rural,132.22,31.6,never smoked
13394,52380,Male,47.0,0,0,No,Govt_job,Urban,68.52,25.2,formerly smoked
13395,56196,Female,10.0,0,0,No,children,Urban,58.64,20.4,never smoked
13396,5450,Female,56.0,0,0,Yes,Govt_job,Urban,213.61,55.4,formerly smoked
13397,28375,Female,82.0,1,0,Yes,Private,Urban,91.94,28.9,formerly smoked
13398,27973,Male,40.0,0,0,Yes,Private,Urban,99.16,33.2,never smoked
13399,36271,Female,82.0,0,0,Yes,Private,Urban,79.48,20.6,never smoked

In [105]:
train

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,30669,Male,3.0,0,0,No,children,Rural,95.12,18.0,NaN,0
1,30468,Male,58.0,1,0,Yes,Private,Urban,87.96,39.2,never smoked,0
2,16523,Female,8.0,0,0,No,Private,Urban,110.89,17.6,NaN,0
3,56543,Female,70.0,0,0,Yes,Private,Rural,69.04,35.9,formerly smoked,0
4,46136,Male,14.0,0,0,No,Never_worked,Rural,161.28,19.1,NaN,0
5,32257,Female,47.0,0,0,Yes,Private,Urban,210.95,50.1,NaN,0
6,52800,Female,52.0,0,0,Yes,Private,Urban,77.59,17.7,formerly smoked,0
7,41413,Female,75.0,0,1,Yes,Self-employed,Rural,243.53,27.0,never smoked,0
8,15266,Female,32.0,0,0,Yes,Private,Rural,77.67,32.3,smokes,0
9,28674,Female,74.0,1,0,Yes,Self-employed,Urban,205.84,54.6,never smoked,0
10,10460,Female,79.0,0,0,Yes,Govt_job,Urban,77.08,35.0,NaN,0
11,64908,Male,79.0,0,1,Yes,Private,Urban,57.08,22.0,formerly smoked,0
12,63884,Female,37.0,0,0,Yes,Private,Rural,162.96,39.4,never smoked,0
13,37893,Female,37.0,0,0,Yes,Private,Rural,73.50,26.1,formerly smoked,0
14,67855,Female,40.0,0,0,Yes,Private,Rural,95.04,42.4,never smoked,0
15,25774,Male,35.0,0,0,No,Private,Rural,85.37,33.0,never smoked,0
16,19584,Female,20.0,0,0,No,Private,Urban,84.62,19.7,smokes,0
17,24447,Female,42.0,0,0,Yes,Private,Rural,82.67,22.5,never smoked,0
18,49589,Female,44.0,0,0,Yes,Govt_job,Urban,57.33,24.6,smokes,0
19,17986,Female,79.0,0,1,Yes,Self-employed,Urban,67.84,25.2,smokes,0
20,29217,Female,65.0,1,0,Yes,Private,Rural,75.70,41.8,NaN,0
21,72911,Female,57.0,1,0,Yes,Private,Rural,129.54,60.9,smokes,0
22,47175,Female,49.0,0,0,Yes,Private,Rural,60.22,31.5,smokes,0
23,4057,Male,71.0,0,0,Yes,Private,Urban,198.21,27.3,formerly smoked,0
24,48588,Female,59.0,0,0,Yes,Private,Urban,109.82,23.7,never smoked,0
25,70336,Female,25.0,0,0,Yes,Private,Urban,60.84,24.5,never smoked,0
26,66767,Female,67.0,0,0,Yes,Govt_job,Rural,94.61,28.4,smokes,0
27,45801,Female,38.0,0,0,No,Private,Rural,97.49,26.9,never smoked,0
28,36275,Female,54.0,0,0,Yes,Private,Rural,206.72,26.7,never smoked,0
29,11577,Female,70.0,0,0,Yes,Self-employed,Rural,214.45,31.2,never smoked,0
...,...,...,...,...,...,...,...,...,...,...,...,...
29971,45897,Male,37.0,1,0,Yes,Govt_job,Rural,129.81,32.6,formerly smoked,0
29972,31977,Female,28.0,0,0,No,Private,Urban,81.32,42.5,smokes,0
29973,64163,Female,81.0,0,0,Yes,Self-employed,Rural,135.53,19.0,never smoked,0
29974,51817,Female,23.0,0,0,No,Private,Urban,84.39,27.1,never smoked,0
29975,52557,Female,21.0,0,0,Yes,Private,Urban,60.45,23.6,smokes,0
29976,41737,Male,24.0,0,0,Yes,Private,Urban,86.54,26.3,never smoked,0
29977,10963,Female,35.0,0,0,Yes,Govt_job,Rural,77.69,26.7,never smoked,0
29978,43083,Female,46.0,0,0,Yes,Private,Urban,67.16,28.8,NaN,0
29979,51382,Female,45.0,0,0,Yes,Self-employed,Urban,76.09,31.5,never smoked,0
29980,25077,Female,45.0,0,0,Yes,Govt_job,Urban,75.94,28.3,smokes,0
29981,7154,Female,52.0,0,0,Yes,Private,Rural,93.94,20.5,formerly smoked,0
29982,6557,Male,22.0,0,0,Yes,Private,Rural,75.57,34.5,formerly smoked,0
29983,34547,Female,42.0,0,0,No,Private,Rural,85.00,45.8,NaN,0
29984,41539,Female,61.0,0,0,Yes,Private,Rural,65.95,33.9,NaN,0
29985,57990,Male,12.0,0,0,No,children,Urban,109.19,20.9,NaN,0
29986,61989,Female,61.0,0,0,Yes,Self-employed,Rural,210.65,NaN,smokes,0
29987,13742,Female,8.0,0,0,No,children,Urban,73.30,14.6,NaN,0
29988,38851,Male,53.0,1,0,Yes,Self-employed,Urban,188.76,36.0,never smoked,0
29989,47953,Male,13.0,0,0,No,children,Urban,111.45,18.2,never smoked,0
29990,22692,Male,41.0,0,0,Yes,Private,Rural,97.50,39.5,never smoked,0
29991,25503,Female,8.0,0,0,No,children,Urban,85.00,25.2,NaN,0
29992,27036,Female,5.0,0,0,No,children,Urban,106.98,16.1,NaN,0
29993,53877,Female,43.0,0,0,Yes,Govt_job,Urban,131.95,30.0,NaN,0
29994,3856,Female,52.0,1,0,Yes,Private,Rural,71.17,36.1,never smoked,0
29995,32069,Female,36.0,0,0,No,Govt_job,Urban,191.32,45.9,never smoked,0
29996,72228,Female,48.0,1,0,No,Govt_job,Rural,119.19,34.3,never smoked,0
29997,14747,Male,72.0,0,0,Yes,Self-employed,Urban,86.83,34.8,NaN,0
29998,50636,Female,20.0,0,0,No,Private,Rural,67.76,19.7,never smoked,0
29999,43161,Female,27.0,0,0,No,Private,Urban,82.65,22.5,never smoked,0
30000,37061,Male,19.0,0,0,No,Private,Rural,92.61,16.8,never smoked,0

In [106]:
sample

          id  stroke
0      37061     0.5
1      42333     0.5
2      58964     0.5
3      34063     0.5
4      43682     0.5
5       9789     0.5
6       6626     0.5
7      12566     0.5
8      27269     0.5
9      47282     0.5
10     23349     0.5
11     34659     0.5
12     63488     0.5
13     69526     0.5
14     14741     0.5
15      1463     0.5
16     40038     0.5
17     60343     0.5
18     15557     0.5
19     43345     0.5
20     31335     0.5
21     17847     0.5
22     14492     0.5
23     14340     0.5
24     54152     0.5
25     12295     0.5
26     40539     0.5
27     26581     0.5
28     25700     0.5
29     72040     0.5
...      ...     ...
13370   8908     0.5
13371  18119     0.5
13372  45066     0.5
13373   2712     0.5
13374  35172     0.5
13375  51452     0.5
13376  65913     0.5
13377  29122     0.5
13378  12555     0.5
13379  13530     0.5
13380  46293     0.5
13381  57176     0.5
13382  35179     0.5
13383  38020     0.5
13384  44814     0.5
13385   5366     0.5
13386  18828     0.5
13387  25888     0.5
13388  31321     0.5
13389  30759     0.5
13390  10096     0.5
13391  30077     0.5
13392  45266     0.5
13393  69344     0.5
13394  52380     0.5
13395  56196     0.5
13396   5450     0.5
13397  28375     0.5
13398  27973     0.5
13399  36271     0.5

[13400 rows x 2 columns]

In [107]:
feautures_list = ['age', 'avg_glucose_level', 'bmi']

In [108]:
train.shape

(30001, 12)

In [109]:
np.sum(pd.isnull(train['bmi']))# считаем количество неопределенных значений

1017

In [110]:
mean_bmi = train['bmi'].mean()
train['bmi'] = train['bmi'].fillna(mean_bmi)
test['bmi'] = test['bmi'].fillna(mean_bmi)# заменяем их средними значениями в тестовой и обучающей выборках

In [111]:
train_part1 = train.loc[0:15000, : ].copy()
train_part2 = train.loc[15000:, : ].copy() #делим датасет на две равные части

In [112]:
from sklearn.linear_model import LogisticRegression

In [113]:
log_reg_1 = LogisticRegression(random_state=0, solver='lbfgs',
                     )
log_reg_1.fit(X = train_part1.loc[:,feautures_list ], y= train_part1.loc[:, 'stroke'])
# создаем логистическую функцию и тренируем модель на первой половине выборки, то есть проводим кросс-валидацию, для того чтобы
#избежать переобучения модели

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [114]:
prediction_on_part2 = log_reg_1.predict_proba(X = train_part2.loc[:,feautures_list ] )[:,1]
#строим предсказание значения stroke на второй половине обучающей выборки

In [115]:
from sklearn.metrics import accuracy_score #импортируем бибилотеку для создания метрики

In [116]:
accuracy_score(train_part2['stroke']  ,
                      (prediction_on_part2 > train['stroke'].mean())*1) 
# вычисляем метрику близости предсказанных значений и известных значений для второй половины обучающей выборки

0.7400173321778548

In [117]:
log_reg_2 = LogisticRegression(random_state=0, solver='lbfgs',
                     )
log_reg_2.fit(X = train_part2.loc[:,feautures_list ], y= train_part2.loc[:, 'stroke'])
# создаем модель логистической регрессии для второй половины обучающей выборки, то есть проводим кросс-валидацию

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [118]:
prediction_on_part1 = log_reg_2.predict_proba(X = train_part1.loc[:,feautures_list ] )[:,1]

In [119]:
accuracy_score(train_part1['stroke']  ,
                      (prediction_on_part1 > train['stroke'].mean())*1)

0.7172855142990467

In [120]:
# видим, что в первом случае значение выше, поэтому выбираем первую модель и соответствующие ей гиперпараметры
score=[accuracy_score(train_part2['stroke']  ,
                      (prediction_on_part2 > train['stroke'].mean())*1),accuracy_score(train_part1['stroke']  ,
                      (prediction_on_part1 > train['stroke'].mean())*1)]

In [121]:
score

[0.7400173321778548, 0.7172855142990467]

In [122]:
np.mean(score)

0.7286514232384508

In [123]:
# можно features менять и в зависимости от значения метрики смотреть какие параметры оказывают наибольшее влияние на результат
# предварительно заменяем все категориальные переменные на числовые

In [124]:
for i in train['work_type'].unique():
    print(i)
    train['work_type_is_{}'.format(i)] = (train['work_type'] == i)*1
    test['work_type_is_{}'.format(i)] = (test['work_type'] == i)*1

children
Private
Never_worked
Self-employed
Govt_job

In [125]:
(train.groupby(['smoking_status'])['stroke'].agg(['mean'])).to_dict()

{'mean': {'formerly smoked': 0.027783137179239824,
  'never smoked': 0.01723982308872642,
  'smokes': 0.01972386587771203}}

In [126]:
smoking_status_target_enc_dict = (train.groupby(['smoking_status'])['stroke'].agg(['mean'])).to_dict()['mean']

In [127]:
train['smoking_status_target_enc'] = train['smoking_status'].replace(smoking_status_target_enc_dict)
test['smoking_status_target_enc'] = test['smoking_status'].replace(smoking_status_target_enc_dict)

In [128]:
train['ever_married'] = train['ever_married'].replace({'Yes':1, 'No':0 })
test['ever_married'] = test['ever_married'].replace({'Yes':1, 'No':0 })

In [129]:
train['Residence_type'] = train['Residence_type'].replace({'Urban':1, 'Rural':0 })
test['Residence_type'] = test['Residence_type'].replace({'Urban':1, 'Rural':0 })

In [130]:
for i in train['smoking_status'].unique():
    print(i)
    train['smoking_status_is_{}'.format(i)] = (train['smoking_status'] == i)*1
    test['smoking_status_is_{}'.format(i)] = (test['smoking_status'] == i)*1

nan
never smoked
formerly smoked
smokes

In [131]:
train.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,...,work_type_is_children,work_type_is_Private,work_type_is_Never_worked,work_type_is_Self-employed,work_type_is_Govt_job,smoking_status_target_enc,smoking_status_is_nan,smoking_status_is_never smoked,smoking_status_is_formerly smoked,smoking_status_is_smokes
0,30669,Male,3.0,0,0,0,children,0,95.12,18.0,...,1,0,0,0,0,NaN,0,0,0,0
1,30468,Male,58.0,1,0,1,Private,1,87.96,39.2,...,0,1,0,0,0,0.017240,0,1,0,0
2,16523,Female,8.0,0,0,0,Private,1,110.89,17.6,...,0,1,0,0,0,NaN,0,0,0,0
3,56543,Female,70.0,0,0,1,Private,0,69.04,35.9,...,0,1,0,0,0,0.027783,0,0,1,0
4,46136,Male,14.0,0,0,0,Never_worked,0,161.28,19.1,...,0,0,1,0,0,NaN,0,0,0,0

In [132]:
gender_target_enc_dict = (train.groupby(['gender'])['stroke'].agg(['mean'])).to_dict()['mean']

train['gender_target_enc'] = train['gender'].replace(gender_target_enc_dict)
test['gender_target_enc'] = test['gender'].replace(gender_target_enc_dict)

In [133]:
all_features = [ 'age', 'hypertension', 'heart_disease', 'ever_married',
        'Residence_type', 'avg_glucose_level', 'bmi',
         'work_type_is_children',
       'work_type_is_Private', 'work_type_is_Never_worked',
       'work_type_is_Self-employed', 'work_type_is_Govt_job',
       'smoking_status_target_enc', 'smoking_status_is_nan',
       'smoking_status_is_never smoked', 'smoking_status_is_formerly smoked',
       'smoking_status_is_smokes', 'gender_target_enc']

In [134]:
from sklearn.model_selection import KFold
from sklearn.metrics import roc_auc_score 
# вводим метрику roc auc и записываем для нее функцию вычисления метрики с использованием модели log_reg_1, кросс-валидации

In [135]:
def my_cross_validation_for_roc_auc( log_reg_1, X, y ,cv=5):
    X = np.array(X.copy())
    y = np.array(y.copy())
    kf = KFold(n_splits=cv)
    kf.get_n_splits(X)
    scores = []
    for train_index, test_index in kf.split(X):
        #print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        
        log_reg_1.fit(X_train, y_train)
        prediction_on_this_fold = log_reg_1.predict_proba(X_test)[:,1]
        
        score = roc_auc_score(y_score=prediction_on_this_fold, y_true=y_test)
        scores.append(score)
        
    return scores
# здесь вычисляются метрики для выборки разбитой равномерно на пять частей, используем кросс-валидацию

In [136]:
features = [  'age',
            'hypertension' , 'heart_disease' , 'ever_married' ,
            'avg_glucose_level' ,'bmi']

In [137]:
scores = my_cross_validation_for_roc_auc(log_reg_1, train[features] , train['stroke'])

D:\JyPyter\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
D:\JyPyter\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

In [138]:
scores
# список вычисленных метрик для каждого случая

[0.8420497759704808,
 0.848366647141066,
 0.8471269478319783,
 0.8541358001635146,
 0.8451441762700042]

In [139]:
np.mean(scores)# среднее значение по всем разбиениям

0.8473646694754088

In [140]:
all_features = [ 'age', 'hypertension', 'heart_disease', 'ever_married',
        'Residence_type', 'avg_glucose_level', 'bmi',
         'work_type_is_children',
       'work_type_is_Private', 'work_type_is_Never_worked',
       'work_type_is_Self-employed', 'work_type_is_Govt_job']
# выбираем все числовые фичи

In [141]:
features_scores = {}
for f in all_features:
    scores = my_cross_validation_for_roc_auc(log_reg_1, train[[f]] , train['stroke'])
    print(f,  np.mean(scores))
    features_scores[f] = np.mean(scores)
    # считаем для них метрику

age 0.8366076869311634
hypertension 0.581615320246325
heart_disease 0.5818777239077606
ever_married 0.6259899654630761
Residence_type 0.49321198951765294
avg_glucose_level 0.6139074419876318
bmi 0.5628027539558931
work_type_is_children 0.5689884334400628
work_type_is_Private 0.48643144589553095
work_type_is_Never_worked 0.5019511976545372
work_type_is_Self-employed 0.5634987850302702
work_type_is_Govt_job 0.4889896401849564

In [142]:
scores = my_cross_validation_for_roc_auc(log_reg_1, train[all_features] , train['stroke'])

D:\JyPyter\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
D:\JyPyter\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
D:\JyPyter\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
D:\JyPyter\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
D:\JyPyter\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)

In [143]:
np.mean(scores)

0.846582333271612

In [144]:
# средние значение метрики для параметров без учета типа занятости выше, значит эти параметры несущественны

In [153]:
feautures_list=[ 'age', 'hypertension', 'heart_disease', 'ever_married',
        'Residence_type', 'avg_glucose_level', 'bmi',
         'work_type_is_children',
       'work_type_is_Private', 'work_type_is_Never_worked',
       'work_type_is_Self-employed', 'work_type_is_Govt_job']

In [154]:
test.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,...,work_type_is_Private,work_type_is_Never_worked,work_type_is_Self-employed,work_type_is_Govt_job,smoking_status_target_enc,smoking_status_is_nan,smoking_status_is_never smoked,smoking_status_is_formerly smoked,smoking_status_is_smokes,gender_target_enc
0,37061,Male,19.0,0,0,0,Private,0,92.61,16.8,...,1,0,0,0,0.017240,0,1,0,0,0.019245
1,42333,Male,53.0,0,0,1,Govt_job,1,94.03,26.5,...,0,0,0,1,NaN,0,0,0,0,0.019245
2,58964,Female,51.0,0,0,1,Private,0,127.22,31.0,...,1,0,0,0,0.019724,0,0,0,1,0.016576
3,34063,Female,17.0,0,0,0,Private,0,112.15,19.8,...,1,0,0,0,NaN,0,0,0,0,0.016576
4,43682,Female,41.0,0,0,1,Govt_job,1,112.17,27.5,...,0,0,0,1,0.017240,0,1,0,0,0.016576

In [155]:
log_reg_1

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [156]:
prediction = log_reg_1.predict_proba(X = test.loc[:,feautures_list ] )[:,1]
# предсказываем значение на тесте, заносим в переменную и записываем в файл для загрузки на kaggle

In [157]:
sample['stroke'] = prediction

In [158]:
sample.to_csv('submi2.csv', index = None ) # на kaggle выдает 0.86, что приблизительно с метрикой совпало

In [ ]:
# теперь применяю метод стохастического градиентного спуска

In [179]:
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [180]:
clf = linear_model.SGDRegressor(max_iter=1000, tol=1e-2)

In [181]:
train_part1 = train.loc[0:15000, : ].copy()
train_part2 = train.loc[15000:, : ].copy()

In [182]:
feautures_list = ['age', 'avg_glucose_level', 'bmi']

In [183]:
clf.fit(X = train_part1.loc[:,feautures_list ], y= train_part1.loc[:, 'stroke'])

SGDRegressor(alpha=0.0001, average=False, early_stopping=False, epsilon=0.1,
             eta0=0.01, fit_intercept=True, l1_ratio=0.15,
             learning_rate='invscaling', loss='squared_loss', max_iter=1000,
             n_iter_no_change=5, penalty='l2', power_t=0.25, random_state=None,
             shuffle=True, tol=0.01, validation_fraction=0.1, verbose=0,
             warm_start=False)

In [184]:
prediction_on_part2 = clf.predict(train_part2.loc[:,feautures_list ] )

In [185]:
prediction_on_part2

array([1.53295013e+12, 1.47783429e+12, 1.14191285e+12, ...,
       1.48713111e+12, 1.74472203e+12, 2.14588063e+12])

In [193]:
prediction = clf.predict(X = test.loc[:,feautures_list ] )

In [194]:
sample['stroke'] = prediction

In [195]:
sample.to_csv('submi2.csv(9)', index = None )
# здесь все действия будут как в пункте с логистической регрессией

In [202]:
# последняя часть просто линейная регрессия
sample = pd.read_csv ("C:\\Users\\bubbl\\Desktop\\Data\\sample_submission.csv")
test = pd.read_csv("C:\\Users\\bubbl\\Desktop\\Data\\test.csv")
train = pd.read_csv("C:\\Users\\bubbl\\Desktop\\Data\\train.csv")
train['bmi'] = train['bmi'].fillna(0)
test['bmi'] = test['bmi'].fillna(0)

In [203]:
train['smoking_status'].fillna('nan').value_counts()

never smoked       11079
nan                 9176
formerly smoked     5183
smokes              4563
Name: smoking_status, dtype: int64

In [204]:
ever_married_dict = {'Yes': 1, 'No':0 }

In [205]:
gender_dict={'Male':1,'Female':-1,'Other':0}

In [206]:
train['ever_married'] =train['ever_married'].replace(ever_married_dict)
test['ever_married'] = test['ever_married'].replace(ever_married_dict)

In [207]:
train['gender'] =train['gender'].replace(gender_dict)
test['gender'] = test['gender'].replace(ender_dict)

In [208]:
train['Residence_type'] = train['Residence_type'].replace({'Urban':1, 'Rural':0 })
test['Residence_type'] = test['Residence_type'].replace({'Urban':1, 'Rural':0 })

In [209]:
feautures_list = ['Residence_type','age', 'avg_glucose_level', 'bmi', 'ever_married','hypertension','heart_disease','gender']

In [210]:
clf = linear_model.SGDClassifier(max_iter=1000,  loss='log', penalty = 'l1')
clf.fit(train[feautures_list], train['stroke'])

SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='log', max_iter=1000,
              n_iter_no_change=5, n_jobs=None, penalty='l1', power_t=0.5,
              random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [211]:
clf.predict_proba(test[feautures_list])

array([[1.00000000e+00, 2.45959306e-69],
       [1.00000000e+00, 1.98129428e-48],
       [1.00000000e+00, 2.14190986e-50],
       ...,
       [1.00000000e+00, 5.34603652e-18],
       [1.00000000e+00, 5.19106509e-63],
       [1.00000000e+00, 7.24987217e-19]])

In [214]:
prediction = clf.predict_proba(test[feautures_list])[:,1]

In [215]:
sample['stroke'] = prediction

In [216]:
sample.to_csv('submi2.csv(10)', index = None )

In [217]:
# здесь наибольший score получается, если заменить все null значения в bmi на 0, перевод категориальных переменных в числовую форму 
# и их использование понижают значение на kaggle, max=0.87769

In [218]:
def my_cross_validation_for_roc_auc( clf, X, y ,cv=5):
    X = np.array(X.copy())
    y = np.array(y.copy())
    kf = KFold(n_splits=cv)
    kf.get_n_splits(X)
    scores = []
    for train_index, test_index in kf.split(X):
        #print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = X[train_index], X[test_index]
        y_train, y_test = y[train_index], y[test_index]
        
        clf.fit(X_train, y_train)
        prediction_on_this_fold = clf.predict_proba(X_test)[:,1]
        
        score = roc_auc_score(y_score=prediction_on_this_fold, y_true=y_test)
        scores.append(score)
        
    return scores

In [219]:
scores = my_cross_validation_for_roc_auc(clf, train[feautures_list] , train['stroke'])

In [220]:
scores

[0.8369068523253544,
 0.8129545366809947,
 0.8470113835252935,
 0.8533458943573613,
 0.8429580879912005]

In [221]:
np.mean(scores)

0.8386353509760409

In [ ]:
# значение на kaggel превышает усредненное значение метрик: 0.8386353509760409 и 0.87769
# у меня лучший score получился с линейной регрессией, основные параметры, влиящие на результат:gender age hypertension heart_disease ever_marriedgender age hypertension heart_disease ever_married